site_name: VoiSona 用户指南
site_description: 非官方的 VoiSona 用户指南中文版翻译
repo_url: https://github.com/CeVIO-User-Guide-Unofficial/VoiSona
repo_name: CUGU/VoiSona

# Theme
theme:
  custom_dir: overrides                  # This is where the customization of the theme lives
  name: material
  features:
    - announce.dismiss
    - content.tooltips
    - content.code.annotate
    - content.code.copy
    - navigation.sections
    - navigation.expand
    - navigation.tabs
    - navigation.tabs.sticky
    - navigation.top
    - navigation.footer
    - toc.follow
    - toc.integrate
  icon:
    logo: fontawesome/solid/book
    favicon: images/c-solid.png
    repo: fontawesome/brands/github
  language: zh
  palette:
    - scheme: slate
      primary: orange
      accent: yellow

extra:
  social:
  - icon: fontawesome/brands/twitter 
    link: https://twitter.com/VoiSonaOfficial"
    name: X（旧 Twitter）上的 VoiSona
  - icon: material/web
    link: https://voisona.com/
    name: VoiSona官方网址

# CSS
extra_css:
  - material/assets/stylesheets/extra.css
  - material/assets/stylesheets/footer.css

# Extensions
markdown_extensions:
  - abbr
  - attr_list
  - admonition
  - def_list
  - footnotes
  - md_in_html
  - pymdownx.caret
  - pymdownx.details
  - pymdownx.emoji:
      emoji_index: !!python/name:material.extensions.emoji.twemoji
      emoji_generator: !!python/name:material.extensions.emoji.to_svg
  - pymdownx.highlight:
      anchor_linenums: true
  - pymdownx.inlinehilite
  - pymdownx.keys:
      key_map:
        mouse-wheel-up-down: "鼠标滚轮↕"
  - pymdownx.snippets
  - pymdownx.superfences
  - pymdownx.tilde
  - pymdownx.tabbed:
      alternate_style: true 
  - tables
  - toc:
      toc_depth: 6

plugins:
  - search:
      separator: '[\s\u200b\-]'
  - glightbox
  - git-revision-date-localized:
      type: date
      enable_creation_date: true
  # - offline:
  #     enabled: !ENV [OFFLINE, false]
  #- privacy:
  #    links_attr_map:
  #      target: _blank

# Contents
nav:
  - 首页: index.md
  - VoiSona Song:
    - 用户指南: song/manual.md
    - 快速入门: song/quickstart.md
    - 安装 VoiSona: song/install.md
    - 启动 VoiSona: song/launch.md
    - 登录: song/login.md
    - 选择声库: song/select-voice.md
    - 编辑乐谱: song/edit-score.md
    - 调整参数: song/adjust-params.md
    - 导入与导出: song/import-export.md
    - 环境设置: song/settings.md
    - 常见问题: song/faq.md
  - VoiSona Talk:
    - 用户指南: talk/manual.md
    - 快速入门: talk/quickstart.md
    - 安装 VoiSona: talk/install.md
    - 登录: talk/login.md
    - 选择声库: talk/select-voice.md
    - 输入台词: talk/enter-sentence.md
    - 编辑台词: talk/edit-sentence.md
    - 调整参数: talk/adjust-params.md
    - 导入与导出: talk/import-export.md
    - 环境设置: talk/settings.md
    - REST API 教程: talk/rest-api.md
    - 常见问题: talk/faq.md